pipeline:
  jar:
    image: azul/zulu-openjdk-debian:8
    commands:
      - apt-get update && apt-get install curl -y
      - ./sbt assembly

  publishImage:
    image: plugins/docker
    repo: registry.usw.co/cloud/linkerd-zipkin
    tags: [ "latest" ]
    when:
      branch: master
      event: push
